### ISSUE TITLE
Not seeing events via Node script

### ISSUE THREAD

**Issue by abea** [greenhousecode/meh-activity-logger#5]
I think I have everything set up correctly, but I'm not seeing events in my Google Analytics account. This is in a CLI Node script that's otherwise running well and doing its job. The response looks good, but I don't see any action in GA. I can confirm that the "UA" ID is correct.

Can you see what I might have wrong here?

```javascript
const logger = require('meh-activity-logger').default('UA-xxxxxxxxx-5');

util.sendAnalyticsEvent = async function (command) {
  const { event } = logger;

  const params = {
    userId: 'anon',
    action: 'exec',
    label: command,
    appName: 'app-cli',
    appVersion: cliVersion
  };
  // {
  //   userId: 'anon',
  //   action: 'exec',
  //   label: 'create-piece',
  //   appName: 'app-cli',
  //   appVersion: '2.3.4'
  // }

  try {
    const resp = await event(params);
    console.log('👍', resp);
  } catch (err) {
    if (err) {
      console.error('👎', err);
    }
  }
};
```

The response is:
```
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object]
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://www.google-analytics.com/collect',
    status: 200,
    statusText: 'OK',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```

**Comment by rick-stevens** [comment]
Hey @abea, I can't see an issue with the syntax here. Your response seems to hit GA as well. Since you're sending an event measurement here and not a pageview, have you checked the correct report in GA? Specifically: **Reporting** > **Behaviour** > **Events** with the correct date range of course.

**Comment by abea** [comment]
I was looking at the right report. I'm not sure what was happening. I switched to another package to get it ready for a release, but I want to come back and try to get it working with this one since it's more specifically what we need. I will update when I am able to do that.

As an aside, what does "meh" refer to?

**Comment by rick-stevens** [comment]
You could try [debugging](https://github.com/greenhousecode/meh-activity-logger/blob/master/src/actions/sendGaMeasurement.js#L20-L22) to see Google Analytics' response. It's set up to automatically dry-run hit Google's debug endpoint when the [Document Host Name](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dh) equals `"localhost"` or `"127.0.0.1"` like so:
```js
const resp = await event({
  userId: 'anon',
  action: 'exec',
  label: 'create-piece',
  appName: 'app-cli',
  appVersion: '2.3.4',
  dh: 'localhost'
});

const result = await resp.json();
console.log('Response from Google:', result);
```

Hope it helps!

"meh" stands for a subdivision in our company called Marketing Engineering Hub. This library was meant to serve our opinionated needs, but we decided to publish it anyway.

**Comment by rick-stevens** [comment]
Hi @abea, I've released a new patch where the user-agent gets a default value if not set. This is required when not using the Express middleware since that one grabs it from the request object. This should fix your issue!

**Comment by abea** [comment]
That's working! Thanks.

**Comment by rick-stevens** [comment]
Great!
